### ISSUE TITLE
add macOS support

### ISSUE THREAD

**Issue by donjonsn** [omura-llc/adzap#14]
It is great to see some updates, but it would be even greater to have them also on MacOS' Safari.

**Comment by omura-llc** [comment]
Hi. Please see #1. Sorry to report a macOS version is unlikely anytime soon, although it is the top request at the moment. There was some macOS code that came with the original version of this project (#12), but it wasn't working as a native macOS app or a Catalyst app, due to the addition of UIKit features. I would welcome a pull request if anyone with macOS dev experience has the time. Otherwise I will keep it in mind if I have extra cycles in the future.

**Comment by omura-llc** [comment]
@donjonsn FYI I reopened #1 so people can more easily find the feature request. Feel free to give a thumbs up there. Hopefully we can get to it at some point.
